# Generated by Django 4.2.7 on 2023-11-03 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_questionnaire_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.questionnaire', verbose_name='Мастер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****'), (0, 'Без звезд')], default=0, verbose_name='Оценка'),
        ),
    ]
