# Generated by Django 4.2.7 on 2023-11-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_review_questionnaire_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='users.questionnaire', verbose_name='Мастер'),
        ),
    ]
