# Generated by Django 4.2.7 on 2023-11-02 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_joined_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name=400)),
                ('activity', models.CharField(max_length=100)),
                ('work_experience', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('social', models.CharField(max_length=100)),
                ('schedule', models.TimeField()),
                ('schedule_end', models.TimeField()),
                ('area', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анкета',
            },
        ),
    ]
