# Generated by Django 4.2.7 on 2023-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_review_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='image',
            field=models.ImageField(null=True, upload_to='media/questionnaire/', verbose_name='Фото'),
        ),
    ]
