# Generated by Django 4.2.7 on 2023-11-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_questionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Анкеты', 'verbose_name_plural': 'Анкета'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
