# Generated by Django 4.2.7 on 2023-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_questionnaire_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='area',
            field=models.CharField(choices=[('Моссовет', 'Моссовет'), ('Цум', 'Цум'), ('Дордой', 'Дордой'), ('Ак ордо', 'Ак ордо'), ('1-мкр', '1-мкр'), ('Восток 5', 'Восток 5')], max_length=100, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='language',
            field=models.CharField(choices=[('RUS', 'RUS'), ('KG', 'KG'), ('ENG', 'ENG')], max_length=100, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='work_experience',
            field=models.CharField(choices=[('Стажер', 'Стажер'), ('Менее 6 месяцев', 'Менее 6 месяцев'), ('1 год', '1 год'), ('1-3 года', '1-3 года'), ('3-5 года', '3-5 года'), ('Более 5 года', 'Более 5 года')], max_length=100, verbose_name='Стаж работы'),
        ),
    ]
