# Generated by Django 4.2.7 on 2023-11-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_questionnaire_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
