# Generated by Django 4.2.7 on 2023-11-02 10:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_questionnaire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='activity',
            field=models.CharField(max_length=100, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='area',
            field=models.CharField(choices=[('Моссовет', 'Моссовет'), ('Цум', 'Цум'), ('Дордой', 'Дордой'), ('Ак ордо', 'Ак ордо'), ('1-мкр', '1-мкр'), ('Восток 5', 'Восток 5')], max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Последняя изминение'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='O себе'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='language',
            field=models.CharField(choices=[('RUS', 'RUS'), ('KG', 'KG'), ('ENG', 'ENG')], max_length=100, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='schedule',
            field=models.TimeField(null=True, verbose_name='Начало график работы'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='schedule_end',
            field=models.TimeField(null=True, verbose_name='Конец график работы'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='social',
            field=models.URLField(max_length=100, null=True, verbose_name='Соц сети'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='work_experience',
            field=models.CharField(choices=[('Стажер', 'Стажер'), ('Менее 6 месяцев', 'Менее 6 месяцев'), ('1 год', '1 год'), ('1-3 года', '1-3 года'), ('3-5 года', '3-5 года'), ('Более 5 года', 'Более 5 года')], max_length=100, null=True, verbose_name='Стаж работы'),
        ),
    ]
